### ISSUE TITLE
Allow to obfuscate or omit db.statement

### ISSUE THREAD

**Issue by arielvalentin** [opentracing-contrib/ruby-redis-instrumentation#6]
In some cases the `db.statement` contain parameters that are sensitive or contain PII. 

It would be nice to add the ability to scrub the values or add logic to omit `db.statement` property altogether.

**Comment by mpetazzoni** [comment]
Providing metadata obfuscation capabilities in every single instrumentation shim might end up being quite cumbersome. A more common solution is to obfuscate/manipulate/remove metadata at the collector level.

The OpenCensus collector (https://opencensus.io/service/components/collector/) and SignalFx's Gateway (https://github.com/signalfx/integrations/tree/release/gateway#obfuscating-span-tag-metadata) for example both contain this functionality.

**Comment by arielvalentin** [comment]
@mpetazzoni thanks for pointing that out
